 class PricesRunner{
	 public static void main(String...products){
		 
		 int rice = 150;
		 int dal = 250;
		 int colgate = 20;
		 int brush = 20;
		 int soap = 30;
		 int chees = 50;
		 int butter = 245;
		 int redLabel = 420;												// Array Program
		 int tataTea = 395;
		 int bournvita = 355;
		 int protineX = 572;
		 int horlicks = 224;
		 int boost = 294;
		 int thumsUp = 70;
		 int sprite = 57;
		 int cocaCola = 60;
		 int fanta = 65;
		 int redBull = 120;
		 int lays = 60;
		 int maggi = 30;
		 int dairyMilk = 120;
		 int goodDay = 20;
		 int surfExcel = 50;
		 int gilletteMach = 469;
		 int pickles = 175;
		 int kissan = 190;
		 int lionDates = 152;
		 int tataSalt = 24;
		 int atta = 437;
		 int allOut = 90;
		 int goodNight = 10;
		 int reynoldsPen = 30;
		 int vim = 30;
		 int bingo = 20;
		 int nivea = 150;		 
		 int axe = 250;
		 int fog = 150;
		 int parachuteOil = 105;
		 int faceWasher = 120;
		 int parleG = 10;
		 int sunFeast = 10;
		 int pondsPowder = 20;
		 int wildStone = 30;
		 int ragi = 250;
		 int otts = 150;
		 int ruchiGold = 80;
		 int clinicPlus = 10;
	 
			int[] productsPrices = {ragi,redBull,redLabel,reynoldsPen,rice,ruchiGold,allOut,atta,axe,soap,sprite,sunFeast,surfExcel,dairyMilk,dal,faceWasher,
					fanta,fog,gilletteMach,goodDay,goodNight,horlicks,kissan,lays,lionDates,chees,clinicPlus,cocaCola,colgate,vim,bingo,boost,bournvita,brush,
					butter,nivea,maggi,wildStone,tataSalt,tataTea,thumsUp,otts,parachuteOil,parleG,pickles,pondsPowder,protineX};
			int count = productsPrices.length;
			System.out.println("totalcount :"+ count);
	 
		int ref0 = productsPrices[0];
		int ref1 = productsPrices[1];
		int ref2 = productsPrices[2];
		int ref3 = productsPrices[3];
		int ref4 = productsPrices[4];
		int ref5 = productsPrices[5];
		int ref6 = productsPrices[6];
		int ref7 = productsPrices[7];
		int ref8 = productsPrices[8];
		int ref9 = productsPrices[9];
		int ref10 = productsPrices[10];
		int ref11 = productsPrices[11];
		int ref12 = productsPrices[12];
		int ref13 = productsPrices[13];
		int ref14 = productsPrices[14];
		int ref15 = productsPrices[15];
		int ref16 = productsPrices[16];
		int ref17 = productsPrices[17];
		int ref18 = productsPrices[18];
		int ref19 = productsPrices[19];
		int ref20 = productsPrices[20];
		int ref21 = productsPrices[21];
		int ref22 = productsPrices[22];
		int ref23 = productsPrices[23];
		int ref24 = productsPrices[24];
		int ref25 = productsPrices[25];
		int ref26 = productsPrices[26];
		int ref27 = productsPrices[27];
		int ref28 = productsPrices[28];
		int ref29 = productsPrices[29];
		int ref30 = productsPrices[30];
		int ref31 = productsPrices[31];
		int ref32 = productsPrices[32];
		int ref33 = productsPrices[33];
		int ref34 = productsPrices[34];
		int ref35 = productsPrices[35];
		int ref36 = productsPrices[36];
		int ref37 = productsPrices[37];
		int ref38 = productsPrices[38];
		int ref39 = productsPrices[39];
		int ref40 = productsPrices[40];
		int ref41 = productsPrices[41];
		int ref42 = productsPrices[42];
		int ref43 = productsPrices[43];
		int ref44 = productsPrices[44];
		int ref45 = productsPrices[45];
		int ref46 = productsPrices[46];
		System.out.println("at index ref 0 :"+ref0);
		System.out.println("at index ref 1 :"+ref1);
		System.out.println("at index ref 2 :"+ref2);
		System.out.println("at index ref 3 :"+ref3);
		System.out.println("at index ref 4 :"+ref4);
	    System.out.println("at index ref 5 :"+ref5);
		System.out.println("at index ref 6 :"+ref6);
		System.out.println("at index ref 7 :"+ref7);
		System.out.println("at index ref 8 :"+ref8);
		System.out.println("at index ref 9 :"+ref9);
		System.out.println("at index ref 10 :"+ref10);
		System.out.println("at index ref 11 :"+ref11);
		System.out.println("at index ref 12 :"+ref12);
		System.out.println("at index ref 13 :"+ref13);
		System.out.println("at index ref 14:"+ref14);
		System.out.println("at index ref 15 :"+ref15);
		System.out.println("at index ref 16 :"+ref16);
		System.out.println("at index ref 17 :"+ref17);
		System.out.println("at index ref 18 :"+ref18);
		System.out.println("at index ref 19 :"+ref19);
		System.out.println("at index ref 20 :"+ref20);
		System.out.println("at index ref 21 :"+ref21);
		System.out.println("at index ref 22 :"+ref22);
		System.out.println("at index ref 23 :"+ref23);
		System.out.println("at index ref 24 :"+ref24);
		System.out.println("at index ref 25 :"+ref25);
		System.out.println("at index ref 26 :"+ref26);
		System.out.println("at index ref 27 :"+ref27);
		System.out.println("at index ref 28 :"+ref28);
		System.out.println("at index ref 29 :"+ref29);
		System.out.println("at index ref 30 :"+ref30);
		System.out.println("at index ref 31 :"+ref31);
		System.out.println("at index ref 32 :"+ref32);
		System.out.println("at index ref 33 :"+ref33);
		System.out.println("at index ref 34 :"+ref34);
		System.out.println("at index ref 35 :"+ref35);
		System.out.println("at index ref 36 :"+ref36);
		System.out.println("at index ref 37 :"+ref37);
		System.out.println("at index ref 38 :"+ref38);
		System.out.println("at index ref 39 :"+ref39);
		System.out.println("at index ref 40 :"+ref40);
		System.out.println("at index ref 41 :"+ref41);
		System.out.println("at index ref 42 :"+ref42);
		System.out.println("at index ref 43 :"+ref43);
		System.out.println("at index ref 44 :"+ref44);
		System.out.println("at index ref 45 :"+ref45);
		System.out.println("at index ref 46 :"+ref46);
	 }
 }